# Generated by Django 4.0.2 on 2022-02-17 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=120)),
                ('count', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_results', models.IntegerField()),
            ],
        ),
    ]
